### ISSUE TITLE
passive perception not updating

### ISSUE THREAD

**Issue by twied** [ebshimizu/5e-monster-maker#102]
What an absolutely amazing tool, thank you for that!

Could you kindly have a look at monster's passive perception? If I unlock the manual override with the "handyman" button and change the value by either the up/down arrows or entering a new value, the change is not reflected in the generated stat block. If I press enter, tab out of the field oder click somewhere, the value in the input field is reset to its default value.

**Comment by ebshimizu** [comment]
i'll take a look, it's likely just a visual issue for the web renderer

**Comment by ebshimizu** [comment]
yeah the data was being written correctly but not displayed properly. thanks for catching this one! also resolved some of the easier requests you made along with fixing this bug :)
