### ISSUE TITLE
Feature Request: Ability to give custom monsters items

### ISSUE THREAD

**Issue by aknight2015** [ebshimizu/5e-monster-maker#111]
I'd like the ability to give my custom creations custom items and have it all in one stat block. Any chance you could add an "Equipment" field?

**Comment by ebshimizu** [comment]
I think adding in an additional text field that lets you list items is pretty easy, but it wouldn't link up with the stats particularly well (as in if you gave a +1 sword the attacks wouldn't reflect that automatically). A dynamically linked item system would be a much larger undertaking that is unlikely to happen soon, but I can see about the text field.

**Comment by aknight2015** [comment]
That'll work. Sort of like an Inventory field where the DM can put any custom items he's created for the monster. Helps keep things organized.
