### ISSUE TITLE
How to upload?

### ISSUE THREAD

**Issue by bondjimbond** [ebshimizu/5e-monster-maker#112]
I exported a monster in 5emm.json format, hoping to upload on another computer. However, when I click the Open button and browse my files, the file is greyed out and cannot be selected.

Is there a bug in the uploader, or does it only accept a different format that I failed to export?

**Comment by ebshimizu** [comment]
might be a bug in the OS's file open browser. I can loosen the file type filter to fix this quick.

Out of curiosity, which OS are you on? I don't remember which OS has this problem but if the file filter is too strict sometimes it'll fail to allow the files through.
