### ISSUE TITLE
When using 0 dice or d1 dice remove the die calculations

### ISSUE THREAD

**Issue by Alynntheyelloweyed** [ebshimizu/5e-monster-maker#116]
I just found this tool and its pretty great.

One thing I'd like to bring up is that if you have something that does static damage such as 1 slashing damage and 2 fire damage

![image](https://github.com/ebshimizu/5e-monster-maker/assets/30978715/f5da192f-8fff-4ba4-8490-253622221921)

If we are setting these values either with just a 0dX + bonus or X number of D1s it should just say plus 2 fire damage and omit the die roll information.

If anything could you let us override the actual text to remove it ourselves? Currently I use your tool to help me adjust the CR to what I want, then use a different tool for the actual statblock.

**Comment by ebshimizu** [comment]
hey! good call, I can take a look at adjusting the damage formatter to remove a `0dx` field and just return the modifier.

In the mean time, you can actually re-write the attack text however you want already! Click on the button at the very bottom of an attack field to open the custom renderer. You can then populate the custom renderer with the default rendering text with the arrow icon on the right end of the toolbar. The default renderer is the actual text string used to render the attack, replace it as you see fit!

![image](https://github.com/ebshimizu/5e-monster-maker/assets/777098/9298acf1-5159-43e4-af71-080c98d1e649)
