### ISSUE TITLE
[BUG] Error on Loading some monster files.

### ISSUE THREAD

**Issue by Alynntheyelloweyed** [ebshimizu/5e-monster-maker#119]
I was creating a new monster and decided to load in a previous version of the same monster which was met with an error.

Expected `schema` to be an object or boolean
SchemaError: Expected `schema` to be an object or boolean
    at Ft.validate (https://ebshimizu.github.io/5emm/assets/index.44a79dc8.js:6:23946)
    at Mf (https://ebshimizu.github.io/5emm/assets/index.44a79dc8.js:6:26954)
    at FileReader.<anonymous> (https://ebshimizu.github.io/5emm/assets/index.44a79dc8.js:61:14490)

[Smokestick, Small.5emm.json](https://github.com/ebshimizu/5e-monster-maker/files/12895515/Smokestick.Small.5emm.json)

I'm also including the save file for the creature.

I have other save files that work when loading. The ones that fail all fail with the above error.

**Comment by ebshimizu** [comment]
i forgot to add schema v8 to the index when loading monsters, newer monsters will fail to load because the schema lookup fails.

**Comment by ebshimizu** [comment]
fixed in 2.2.7 build 151 which should be live now. refresh a few times if it doesn't say `build 151` at the bottom.
thanks for the catch, I think I wrote schema v8 and then took a break from the project, resulting in the missing key
