### ISSUE TITLE
Bonus Action Section

### ISSUE THREAD

**Issue by stewdaddy70** [ebshimizu/5e-monster-maker#124]
When I was using the website I couldn't find a way to make a section for BA. Is there a way to do that already?

**Comment by ebshimizu** [comment]
yes! it's admittedly a bit hidden, but you can mark any action as a bonus action by clicking the button near the save icon (it's a toggle) 
![image](https://github.com/ebshimizu/5e-monster-maker/assets/777098/3df91ec0-44cb-4103-82fe-e1208987ee45)
