### ISSUE TITLE
\begin{DndMonster} from .tex export is not recogised when using the {dndbook} from rpgtex

### ISSUE THREAD

**Issue by Melvasul** [ebshimizu/5e-monster-maker#129]
Hello there,

I used your custom tool to create homebrew monsters for my 5e campaign.

To have a more concise db I'm putting everything into a .tex file to have a single pdf to use a Campaign Manual

I'm using rpgtex/DND-5e-LaTeX-Template, so I setup everything accordingly, but when trying to add your .tex it generated errors as reported in the log

- LaTeX Error: Environment DndMonster undefined.
- \DndMonsterType [etc.] Undefined control sequence.

```
% Changing book to article will make the footers match on each page,
\documentclass[10pt,twoside,twocolumn,openany,nodeprecatedcode]{dndbook}

\usepackage[english]{babel}
\usepackage[utf8]{inputenc}

\usepackage{lipsum}
\usepackage{listings}

\usepackage{background}
\usepackage{float}
\usepackage{graphicx}
\usepackage{ifoddpage}
\usepackage{multicol}

\usepackage{tikz}
\usepackage[singlelinecheck=false]{caption}
\usepackage{shortvrb}
\usepackage{stfloats}
\usepackage{fp}
\usepackage{xstring}

% Start document
\author{Melvasul}
\title{Campaign Manual}
\date{2024}

\begin{document}

% Your content goes here
\maketitle

\chapter{Monsters}
 \subsection{Bloodflies}
 Bloodflies are large flying insects armed with a poisonous stinger. They are
 usually found in large, but can also be found in grasslands. Their distinct
 sense of smell enables them to detect their prey despite their undeveloped
 visual organs. On the hunt, bloodfly swarms surround their victim and overwhelm
 it with a multitude of attacks. Once their prey is incapacitated, they feed on
 its blood, which is their main source of nourishment.
 \\[1\baselineskip]
 \begin{DndMonster}[]{Bloodfly}
  
	\DndMonsterType{Medium beast, unaligned}
	\DndMonsterBasics[
	  armor-class = {14},
	  hit-points = {\DndDice{6d8+6}},
	  speed = {30 ft. fly}
	]
  
	\DndMonsterAbilityScores[
	  str = 10,
	  dex = 18,
	  con = 12,
	  int = 2,
	  wis = 14,
	  cha = 4,
	]
  
	\DndMonsterDetails[
	  saving-throws = {DEX +6, WIS +4},
	  %skills = {},
	  %damage-vulnerabilities = {},
	  %damage-resistances = {},
	  %damage-immunities = {},
	  %condition-immunities = {},
	  senses = {Passive Perception 12},
	  languages = {},
	  challenge = {1},
	]
  
	% Traits
	% Actions
	\DndMonsterSection{Actions}
	
	\DndMonsterAttack[
		name=Sting,
		distance=melee,
		type=weapon,
		mod=+6,
		reach=5,
		%range=20/60,
		targets=one target,
		dmg=\DndDice{1d6+4},
		dmg-type=piercing,
		plus-dmg={\DndDice{1d4} poison},
		%or-dmg=\DndDice{1d6+2},
		%or-dmg-when={},
		extra={}
	  ]
	% Spellcasting
	
\end{DndMonster}

% End document
\end{document}
```

How would I solve this?

[ValleyOfMines.log](https://github.com/user-attachments/files/16512009/ValleyOfMines.log)

**Comment by ebshimizu** [comment]
hi! sorry for the delay!
Debugging LaTeX stuff is always a bit of a struggle for me. Funnily enough, the `rpgtex` branch does not actually work in my local installation (unsure why, seems like some out of date font packages in there?). So at some point i changed my local installation (texlive 2022) to use https://github.com/ashonit/DND-5e-LaTeX-Template as the dnd template base. That branch has been updated more recently, so i'd give that version of the template a try. If you're still running in to issues, it might be that the template wasn't fully loaded (the error in question here looks like the monster environment was missed somehow)

**Comment by Melvasul** [comment]
After a clean reinstall of my whole texlive environment, I found out it was a problem with the installation not being 100% correctly setup.

Now I'm encountering other problems such as 
```
Package etoolbox Error: Toggle 'bool-bg' undefined
Package etoolbox Error: Toggle 'multitoc' undefined.
Package etoolbox Error: Toggle 'bool-footer-scroll' undefined.
```
but I'm 100% sure they are not related to your splendid tool or the library itself, thank you again!
