### ISSUE TITLE
Legendary Actions not registering to be selected on the drop down

### ISSUE THREAD

**Issue by Clov-er** [ebshimizu/5e-monster-maker#136]
I very well might not be using the tools right, but I have made several legendary actions for a creature but nothing is appearing in the drop-down box. It is grayed out saying "NO ATTACKS OR ACTIONS AVAILABLE" despite having multiple actions selected as "LEGENDARY ONLY." 
![Screenshot 2024-11-24 163423](https://github.com/user-attachments/assets/8455c986-375c-4c65-aff7-ac0f60c360a9)
![Screenshot 2024-11-24 163530](https://github.com/user-attachments/assets/dd67826c-d85b-46d8-98d8-6853d86125da)

**Comment by ebshimizu** [comment]
huh yeah something broke in there when adding new actions. Currently you can work around this particular issue by refreshing the page, and then the dropdown will populate. If you then add a new action, the dropdown will not have the updated attack or action. Will take a look at a fix

**Comment by Clov-er** [comment]
Alright, well thank you very much for making this tool and fixing the issue so quickly
