### ISSUE TITLE
Homebrewery markdown isn't working properly

### ISSUE THREAD

**Issue by Focusek** [ebshimizu/5e-monster-maker#19]
When using Copy Markdown to Clipboard (Homebrewery) feature, after pasting it into homebrewery the HP value is always too low, legendary actions section appears even if monster doesn't have one, and there is missing bracket before the cost of a legendary action. 
And BTW this is the best monster maker I've managed to find so far. Great Job :))

**Comment by ebshimizu** [comment]
hey thanks for checking it out, and thanks for letting me know! Both of these issues were caused by small oversights, so it's a pretty easy fix (hopefully). Should be working now, if not check that the build number at the bottom says 82 or higher and let me know.
