### ISSUE TITLE
For some reason, my JSON's won't load. 

### ISSUE THREAD

**Issue by bland-html** [ebshimizu/5e-monster-maker#33]
I tried some other files of mine, and they loaded up fine. I'm not sure if why these ones are refusing to load
[monstermaker.zip](https://github.com/ebshimizu/5e-monster-maker/files/7274167/monstermaker.zip)
.

**Comment by ebshimizu** [comment]
the flies are failing to validate due to a save in the attack object being null. Not quite sure how that happened but I can adjust the load protocol to fix that up. while i'm at it, i should output the validation errors so this kind of thing isn't a silent failure.

**Comment by ebshimizu** [comment]
this should be fixed now and those files should load :)

**Comment by bland-html** [comment]
Awesome. Thanks!
