### ISSUE TITLE
Directly Edit Statblock

### ISSUE THREAD

**Issue by JCB3rd** [ebshimizu/5e-monster-maker#38]
Adding an option to directly edit the statblock, perhaps as an option immediately before saving it if editing it beforehand would clash with the program, would be nice. The main reason I've found that made me want to suggest this is multiattack details. There are times I want to add notes about limitations or conditions for a creature's multiattack action that I cannot add using this program at the moment. Some examples include the t-rex who cannot target the same creature with both of its bite attack and tail attack, or a creature that attacks first then uses a special action, like the Shambling Mound, instead of vice versa. Currently, if you allow a creature to use a special action and attack, it always says the creature uses the action first then attacks. Being able to directly edit the statblock would also help add details like a creature being blind beyond its blindsight and more.

**Comment by ebshimizu** [comment]
a direct edit system as described might be difficult to implement, but I might be able to put in a "custom formatting" field for specific areas of the stat block. These fields would allow the use of formatting tokens so the stats still update if you change the data. This would be a significant re-write/change for the application, so it might take a while to implement.

I'll keep it in mind though it's a good suggestion and I do intend to get back to tinkering with this project in the near-future,

**Comment by ebshimizu** [comment]
Text rendering system has been updated in version 2, see #69 for a preview
