### ISSUE TITLE
Importing lists of custom templates/spells fails

### ISSUE THREAD

**Issue by ProlificIllithic** [ebshimizu/5e-monster-maker#46]
Trying to move my custom spells and traits templates to my other browser, but it's telling me "load failed, no version detected"
[5emm.zip](https://github.com/ebshimizu/5e-monster-maker/files/8557452/5emm.zip)

**Comment by ebshimizu** [comment]
hmmm unfortunately i'm unable to replicate this. Which browser are you importing to?
That error should only appear for monsters, as the spells and traits aren't versioned (they should be, this codebase needs a re-write soon)
