### ISSUE TITLE
Mythical Actions do not appear.

### ISSUE THREAD

**Issue by JodiSnepvangers** [ebshimizu/5e-monster-maker#48]
Adding Mythical Actions does not work. It appears to open some sort of menu, but that menu is empty and nothing appears on the output sheet. This has been tested on Windows 10, on chrome, Firefox and edge. All show the same behaviour.

**Comment by ebshimizu** [comment]
Mythic actions require the action or attack to exist before anything shows up in the menu. If there are no actions or attacks on the monster, the mythic action menu won't show anything available to add. It's a bit cumbersome but I didn't want to duplicate attack/action entry for that section. To designate something as mythic/legendary only, click the "L" button in the action/attack settings and it'll hide itself from its usual section.

If that's still happening after adding an action, save the monster file and send it to me so I can take a look.

**Comment by ebshimizu** [comment]
Ah yeah I think I can add a "no actions available" message to the dropdown. I'll close this issue when I add that.
