### ISSUE TITLE
Mythical Action Styling

### ISSUE THREAD

**Issue by JodiSnepvangers** [ebshimizu/5e-monster-maker#49]
Hello!

I feel like this is a styling error, but correct me if i am wrong. When using a mythical action, its text is shifted to the right on the left side of the sheet. All other text is nice and flush against the left side of the sheet so it seems kind of odd. Is this done intentionally?

Here is a image to show what i mean:
![image](https://user-images.githubusercontent.com/3314494/169258582-97038ef5-4dc7-40a4-932a-364422fed7bc.png)

EDIT: it seems that this effect also happens with Legendary Actions, so this might be connected:
Here is a image showing what i get, along with a example (green circle) of what i expected it to look like.

![image](https://user-images.githubusercontent.com/3314494/169302945-e4d1ff1f-27f0-480f-984c-4f2b6ef6678b.png)

**Comment by ebshimizu** [comment]
This is actually done intentionally to match the formatting of the published statblocks, which leave the first line unindented. I'm not entirely sure why they're formatted like that, but I kept that here to match the usual formatting.

**Comment by JodiSnepvangers** [comment]
Fair enough. What monster do you have as a example of formatting?i would love to know! i had troubles finding examples of creatures using mythical actions.
But if its correct, then it isnt a issue and this can be closed.

**Comment by ebshimizu** [comment]
that trait first showed up in the Theros source, though you can also see this formatting with any creature that has legendary actions (dragons, etc.)
