### ISSUE TITLE
Additional Damage on Attack Die Type Doesn't Update

### ISSUE THREAD

**Issue by hammy3502** [ebshimizu/5e-monster-maker#73]
If you add an attack, then add additional damage to it, the dropdown menu will not reflect the change, but the preview of the monster on the right hand side will acknowledge the change. Additionally, changing the dropdown of the primary attack's damage die will update all of the additional damage dice's selection in the dropdown menu.

I think the rendering for the additional damage's die type dropdown points to the primary attack's die type rather than its own?

**Comment by ebshimizu** [comment]
good catch, thank you! The issue was as you noted, the additional damage's die dropdown was displaying the value from the primary damage die. This was a visual bug on the editor state, the values were still being inputted correctly behind the scenes.
