### ISSUE TITLE
Ability scores moved out of place when rendering PNG

### ISSUE THREAD

**Issue by SuzuXIII** [ebshimizu/5e-monster-maker#80]
Ability scores move out of place when rendering the stat block as a PNG for unknown reasons. Does not fix on refresh, using Google Chrome.

![Poisonous Snake (PHB)](https://user-images.githubusercontent.com/118045609/201465492-7e6cca1a-a9a8-4ae1-befe-5df34b77c622.png)

**Comment by SuzuXIII** [comment]
Happened again while making a new statblock using the Poisonous Snake as a base. Not sure what's causing this, but it seems to be an issue tied to something I did, I just don't know what.
![Pseudodragon (PHB)](https://user-images.githubusercontent.com/118045609/201466582-97d89cf4-e4ca-4de0-85cf-d24fb279e388.png)

**Comment by ebshimizu** [comment]
duplicate #79 
thanks for the additional report! This is has been reported along with a couple oddities found in the PNG renderer. I'll take a look to see what we can do, might be anything from a recent change in chrome/edge to something that was in the renderer to begin with.

**Comment by SuzuXIII** [comment]
Alright, I'll try rendering it over on Firefox and see what happens.

**Comment by ebshimizu** [comment]
hmm yep looks like a recent chrome/edge change. Wasn't able to reliably reproduce on my desktop until I updated to Edge Version 107.0.1418.42. Will check to see if the library used for that operation also updated or if the formatting can be adjusted to fix the issue

**Comment by ebshimizu** [comment]
stat container wasn't enforcing no-wrap so I added that to ensure the PNG renderer matches in that regard.
while i was at it, I also updated the fonts to be closer matches of published stat blocks.

marking this issue as closed, please re-open if the issue persists :)
