### ISSUE TITLE
Using Reset Monster breaks speed

### ISSUE THREAD

**Issue by SuzuXIII** [ebshimizu/5e-monster-maker#81]
Title, it keeps the speed of the old monster while displaying 30 ft. Attempting to change the speed will completely break it, creating new speeds without displaying it on either the stat block or the editor. Fixes on refresh, using Google Chrome.
![Screenshot 2022-11-12 201857](https://user-images.githubusercontent.com/118045609/201502514-4cc198e3-5f1c-4170-9304-d0c43723d6d8.png)

**Comment by ebshimizu** [comment]
Reproduced. Same issue is occurring with skills (persist after reset but since they don't exist anymore the controls do nothing). Investigating.

**Comment by ebshimizu** [comment]
easy enough fix, thanks for catching this one!
