### ISSUE TITLE
Multiattack calculates repeatedly for N use actions

### ISSUE THREAD

**Issue by SierraKomodo** [ebshimizu/5e-monster-maker#86]
If you create a monster with a multi-attack group that includes an action that can only be performed N times, i.e., 1/day, the offensive CR calculation will ignore this limitation and include 3 turns worth of this multi-attack group.

The expected behavior only includes the multi-attack group once if it includes a 1-time use action.

Discovered this while rolling some boss NPCs based on PC classes/races and attempting to account for action surge.

Export URL for the monster with the noted issue: https://tinyurl.com/2oz3auju

**Comment by ebshimizu** [comment]
thanks for the link, and yep looks like something went wrong with the limited use check. The code at https://github.com/ebshimizu/5e-monster-maker/blob/6a1cc1a5b61b34ed6a2b23ef1381fd16d24c5f7a/src/components/cr/useCr.ts#L187 looks a little suspicious, likely something didn't get ported over correctly when moving the project to typescript. will take a look!

**Comment by ebshimizu** [comment]
this one was actually trickier than I thought, but it should be working as expected now. Note that actions with a "Recharge" value are treated as a single use action. Let me know if it continues to misbehave!
