### ISSUE TITLE
Can't access any of my hundreds of homebrew sheets after 2.0 update

### ISSUE THREAD

**Issue by Zarkkill** [ebshimizu/5e-monster-maker#95]
Title explains it mostly. I cannot access any of my monster sheets that are all homebrew if they were created in the first version. I only have the links to the sheets I didn't download JSONs or PNGs of them but if I try to click on the links they just take me to whatever I had up last in the 2.0 creator. I just really need access to my old sheets in any way I can get it so I can save them in a more secure way lest I lose dozens of hours of homebrewing.

**Comment by ebshimizu** [comment]
hey! sorry to hear that! It sounds like the link format might be slightly off from 1.0 to 2.0, so your data should still be encoded in the URL but the app isn't picking it up. Can you send me one of them so I can see what's happening?

**Comment by Zarkkill** [comment]
happy to, I don't care how it happens I'll be happy just to get access to the sheets again. Here are a couple:

https://tinyurl.com/ybe5y77p

https://tinyurl.com/y2a7flbo

https://tinyurl.com/yedagono

Hopefully we can get them working again and I can just click the link again, but if not, I only require a few to access as I had 99% of the statblocks saved elsewhere, there were just a couple that I hadn't gotten to when the change happened.

**Comment by ebshimizu** [comment]
ah yeah I see the problem immediately. The old links go to `/?data=` where the new links expect `/#/?data=`. The data is all there, and you can manually edit the links to load them while I work on a fix (just add a `#/` before the `?data=` part).

**Comment by ebshimizu** [comment]
verified resolution in 1a91f0ef36de8e739fb0aa2b6c0ce9cb5713b0b4 (2.2.1b139)
Old links should work again! let me know/re-open this issue if they act up. Sometimes refreshing will get the page to behave correctly if it's being stubborn.

(and remember to download json files or copy the full links! I don't know how long tinyurl keeps the link redirects around)
